# -*- coding: utf-8 -*-
# Generated by Django 5.2.14 on 2026-06-04 07:53
"""
tracker/migrations/0001_initial.py
ねこのひげ - 初回マイグレーション（全モデルの土台）

【このマイグレーションがやること】
tracker アプリで使う4つのモデル（=テーブル）を新規作成する。
  1. MedicationRecord  : 服薬記録
  2. PainRecord        : 痛み記録（このアプリのコア機能）
  3. ReminderSetting   : 薬リマインダー設定
  4. WeatherRecord     : 気象記録（Open-Meteoから取得）

【重要：これは "initial" マイグレーション】
  - `initial = True` フラグ付きで、`dependencies = []`（依存なし）
  - つまり、ここがアプリ全体のスタート地点
  - 既に本番DBに適用済みのこのファイルは、絶対に手で書き換えてはいけない
    （後続マイグレーション 0002 以降で AlterField により上書き調整している）

【適用方法】
    python manage.py migrate tracker 0001
    # 通常は最新まで一括適用：
    python manage.py migrate tracker
"""
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    """
    マイグレーション本体クラス。
    Djangoはこのクラスを読み取って、operations を順に実行する。
    """

    # ------------------------------------------------------------
    # initial フラグ
    # ------------------------------------------------------------
    # True を指定することで、Djangoはこれを「アプリの最初のマイグレーション」
    # として認識する。
    # `makemigrations --merge` などで自動生成される追加マイグレーションが
    # このファイルを基準点として扱う。
    initial = True

    # ------------------------------------------------------------
    # 依存関係
    # ------------------------------------------------------------
    # 空リスト = 何にも依存しない（このアプリの起点）。
    # 他アプリのモデルにForeignKeyを張る場合は、ここに対象アプリの
    # マイグレーションを列挙する必要がある。
    dependencies = [
    ]

    # ------------------------------------------------------------
    # 実際にDBに作るテーブルの定義（上から順に CREATE TABLE される）
    # ------------------------------------------------------------
    operations = [

        # ============================================================
        # 1. MedicationRecord（服薬記録）
        # ============================================================
        # 「いつ・何の薬を飲んだか」をシンプルに記録するテーブル。
        # 現UIでは主に管理画面と将来の拡張用として用意されている。
        migrations.CreateModel(
            name='MedicationRecord',
            fields=[
                # 主キー：BigAutoField（64bit整数）
                ('id', models.BigAutoField(auto_created=True, primary_key=True,
                                           serialize=False, verbose_name='ID')),

                # 服用日時：未指定なら現在時刻（timezone.now を default に指定）
                # default に関数オブジェクトを渡すと、レコード作成時に都度呼ばれる
                ('taken_at', models.DateTimeField(default=django.utils.timezone.now,
                                                  verbose_name='服用日時')),

                # 薬名：64文字まで（市販薬の長い名前にも対応できる長さ）
                ('name', models.CharField(max_length=64, verbose_name='薬名')),
            ],
        ),

        # ============================================================
        # 2. PainRecord（痛み記録）★このアプリのコアテーブル
        # ============================================================
        # ユーザが「いつ・どこが・どんな風に・どの程度痛いか」を記録する。
        # 後段で気圧・天気との突き合わせに使う、分析の主役データ。
        #
        # ※ 注意：このマイグレーションでの level/body_part/pain_type の定義は
        #   後続マイグレーション(0002)で AlterField により変更されている。
        #   - level: choices が 3→1 の降順 → 0002で 1→3 の昇順 + 規格揃え
        #   - body_part: 7択 → 0002で choices無しの自由入力に変更
        #   - pain_type: 6択 → 0002で choices無しの自由入力に変更
        #   現状の正確な仕様を知りたい時は最新のマイグレーション or models.pyを参照。
        migrations.CreateModel(
            name='PainRecord',
            fields=[
                # 主キー
                ('id', models.BigAutoField(auto_created=True, primary_key=True,
                                           serialize=False, verbose_name='ID')),

                # 記録日時：未指定なら現在時刻
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now,
                                                     verbose_name='記録日時')),

                # 痛み度：3段階の選択肢
                # ※ 表示順がDB値の降順（3,2,1）になっているのは初版の名残
                #    0002 で 1,2,3 の自然順に整理される
                ('level', models.IntegerField(
                    choices=[(3, 'すごく痛い'), (2, '痛い'), (1, '痛くない')],
                    verbose_name='痛み度',
                )),

                # 痛みの部位：定型7択（初版）
                # 体の代表的な部位をカバー。"other" で逃げ道を用意。
                ('body_part', models.CharField(
                    choices=[
                        ('head', '頭'),
                        ('neck', '首'),
                        ('shoulder', '肩'),
                        ('stomach', 'お腹'),
                        ('leg', '脚'),
                        ('back', '腰'),
                        ('other', 'その他'),
                    ],
                    default='head',
                    max_length=16,
                    verbose_name='痛みの部位',
                )),

                # 痛みの種類：定型6択（初版）
                # 「ズキズキ／チクチク／ズーン...」など擬音語で
                # 痛みの質感を選べるようにしている。
                ('pain_type', models.CharField(
                    choices=[
                        ('throbbing', 'ズキズキ（脈打つ）'),
                        ('stabbing', 'チクチク（刺すような）'),
                        ('dull', 'ズーン（鈍い・重い）'),
                        ('tingling', 'ピリピリ（しびれる）'),
                        ('stiffness', '張る・こわばる'),
                        ('other', 'その他'),
                    ],
                    default='throbbing',
                    max_length=16,
                    verbose_name='痛みの種類',
                )),

                # メモ：任意入力、140文字制限（Twitter初期の文字数感覚）
                # blank=True で空文字を許可、default='' で空をデフォルトに
                ('memo', models.CharField(blank=True, default='',
                                          max_length=140, verbose_name='メモ')),
            ],
        ),

        # ============================================================
        # 3. ReminderSetting（薬リマインダー設定）
        # ============================================================
        # 「何時に何の薬を飲むか」のスケジュール設定。
        # フロントの吹き出し（「次のお薬はXX時だにゃ！」）の根拠データ。
        migrations.CreateModel(
            name='ReminderSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True,
                                           serialize=False, verbose_name='ID')),

                # リマインド時刻：時:分のみ（日付は持たない＝毎日繰り返し前提）
                ('reminder_time', models.TimeField(verbose_name='リマインド時刻')),

                # 薬の種類：64文字（市販薬の長い名前にも対応）
                ('medicine_name', models.CharField(max_length=64,
                                                   verbose_name='薬の種類')),

                # 有効フラグ：False にすると一覧から無効化扱いに
                # （レコードを削除せずに「一時停止」できるように）
                ('is_active', models.BooleanField(default=True,
                                                  verbose_name='有効フラグ')),
            ],
        ),

        # ============================================================
        # 4. WeatherRecord（気象記録）
        # ============================================================
        # Open-Meteo APIから取得した1時間ごとの気象データを蓄積するテーブル。
        # PainRecord との時系列突き合わせの基盤データ。
        migrations.CreateModel(
            name='WeatherRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True,
                                           serialize=False, verbose_name='ID')),

                # 観測日時：★ unique=True
                # → DBレベルで「同じ時刻のレコードは1件まで」を保証
                # → 気象データを取得し直しても重複保存されない仕掛け
                ('observed_at', models.DateTimeField(unique=True,
                                                     verbose_name='観測日時')),

                # 天気コード：Open-Meteoの weathercode 仕様に準拠
                # 0=晴 / 1=主に晴 / 2=曇 / 3=雨 ... など
                ('weather_code', models.IntegerField(verbose_name='天気')),

                # 気温（摂氏）
                ('temperature_c', models.FloatField(verbose_name='気温')),

                # 気圧（hPa）：痛みとの相関を見るキー指標
                ('pressure_hpa', models.FloatField(verbose_name='気圧')),
            ],
        ),
    ]