# -*- coding: utf-8 -*-
# Generated by Django 5.2.14 on 2026-06-05 06:43
"""
tracker/migrations/0002_xxxxx.py
ねこのひげ - 第2回マイグレーション

【このマイグレーションがやること（概要）】
  1. 新規モデル UserLocation を追加（ユーザーの現在地を1レコードで保持）
  2. 全モデルにデフォルト並び順（ordering）を設定
  3. 既存フィールドに verbose_name（管理画面の日本語ラベル）を追加
  4. PainRecord.level を「整数」から「選択肢付き整数」に変更
     （1=痛くない / 2=普通 / 3=痛い）

【重要：マイグレーションファイルとは】
  Djangoが models.py の変更履歴をDBに反映するための「設計図」。
  - `python manage.py makemigrations` で自動生成される
  - `python manage.py migrate` でDBに適用される
  - 一度本番DBに適用したものは原則として手で書き換えてはいけない
    （適用済みDBとの整合性が崩れる）
  - チーム共有時はこのファイルもGitに必ずコミットすること

【適用方法】
    python manage.py migrate tracker
"""
from django.db import migrations, models


class Migration(migrations.Migration):
    """
    マイグレーションの本体クラス。
    Djangoは dependencies の順序を辿って operations を適用する。
    """

    # ------------------------------------------------------------
    # 依存関係
    # ------------------------------------------------------------
    # このマイグレーションを適用する前に必須となる「前提マイグレーション」。
    # ('tracker', '0001_initial') は tracker アプリ最初のマイグレーション（モデル初期定義）。
    # → 0001 が適用済みでないと、この 0002 は走らない。
    dependencies = [
        ('tracker', '0001_initial'),
    ]

    # ------------------------------------------------------------
    # 実際の変更内容（上から順に適用される）
    # ------------------------------------------------------------
    operations = [
        # ============================================================
        # 1. 新規モデル UserLocation を追加
        # ============================================================
        # ユーザーの現在地（緯度・経度）を保存するテーブルを新規作成する。
        # 単一レコード運用（最新の1件だけを更新し続ける）想定。
        # デフォルト値は東京駅近辺（35.6895, 139.6917）。
        migrations.CreateModel(
            name='UserLocation',
            fields=[
                # 主キー：BigAutoField（64bit整数の自動採番）
                ('id', models.BigAutoField(auto_created=True, primary_key=True,
                                           serialize=False, verbose_name='ID')),

                # 緯度（東京駅をデフォルト）
                ('latitude', models.FloatField(default=35.6895, verbose_name='緯度')),

                # 経度（東京駅をデフォルト）
                ('longitude', models.FloatField(default=139.6917, verbose_name='経度')),

                # 位置情報の精度（メートル）。
                # ブラウザのGeolocation APIから受け取る accuracy をそのまま保存。
                # 不明な場合は null/blank を許容。
                ('accuracy_m', models.FloatField(blank=True, null=True, verbose_name='精度(m)')),

                # 最終更新時刻（auto_now=True で save 時に自動更新）
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最終更新')),
            ],
            options={
                # 管理画面での日本語表示名
                'verbose_name': 'ユーザー現在地',
            },
        ),

        # ============================================================
        # 2. 既存モデルにデフォルト並び順（ordering）を設定
        # ============================================================
        # `Meta.ordering` を設定することで、Model.objects.all() の結果が
        # 常に同じ順序で返るようになる（ビュー側で order_by() を書き忘れても
        # 安定した順序で取得できる）。
        # マイナス記号は降順を表す（例：-recorded_at = 新しい順）。

        # 服薬記録：新しい順
        migrations.AlterModelOptions(
            name='medicationrecord',
            options={'ordering': ['-taken_at']},
        ),

        # 痛み記録：新しい順
        migrations.AlterModelOptions(
            name='painrecord',
            options={'ordering': ['-recorded_at']},
        ),

        # リマインダー：時刻の早い順（朝→夜の順に並ぶ）
        migrations.AlterModelOptions(
            name='remindersetting',
            options={'ordering': ['reminder_time']},
        ),

        # 気象記録：新しい順
        migrations.AlterModelOptions(
            name='weatherrecord',
            options={'ordering': ['-observed_at']},
        ),

        # ============================================================
        # 3. 既存フィールドに verbose_name を追加
        # ============================================================
        # verbose_name は管理画面（/admin/）やフォームのラベルで使われる
        # 「人間向けの表示名」。日本語化することで管理画面の可読性が大幅に上がる。
        # データ構造そのものには影響しない（カラム名や型は不変）。

        # --- MedicationRecord（服薬記録）---
        migrations.AlterField(
            model_name='medicationrecord',
            name='name',
            field=models.CharField(max_length=50, verbose_name='薬名'),
        ),
        migrations.AlterField(
            model_name='medicationrecord',
            name='taken_at',
            field=models.DateTimeField(verbose_name='服薬日時'),
        ),

        # --- PainRecord（痛み記録）---
        migrations.AlterField(
            model_name='painrecord',
            name='body_part',
            field=models.CharField(blank=True, max_length=50, verbose_name='部位'),
        ),

        # ★ 重要な変更：level に choices を追加
        #   → 旧：任意の整数を保存可能
        #   → 新：1/2/3 の3択（管理画面でラジオボタン的に表示される）
        #   既存データに 4以上の値があると整合性が崩れる点に注意。
        #   （現在のviewsで 1〜3 にクリップしているので実質的には安全）
        migrations.AlterField(
            model_name='painrecord',
            name='level',
            field=models.PositiveSmallIntegerField(
                choices=[(1, '痛くない'), (2, '普通'), (3, '痛い')],
                default=1,
                verbose_name='痛み度',
            ),
        ),

        migrations.AlterField(
            model_name='painrecord',
            name='memo',
            field=models.CharField(blank=True, max_length=140, verbose_name='メモ'),
        ),
        migrations.AlterField(
            model_name='painrecord',
            name='pain_type',
            field=models.CharField(blank=True, max_length=50, verbose_name='痛みの種類'),
        ),
        migrations.AlterField(
            model_name='painrecord',
            name='recorded_at',
            field=models.DateTimeField(verbose_name='記録日時'),
        ),

        # --- ReminderSetting（薬リマインダー）---
        migrations.AlterField(
            model_name='remindersetting',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='有効'),
        ),
        migrations.AlterField(
            model_name='remindersetting',
            name='medicine_name',
            field=models.CharField(max_length=50, verbose_name='薬名'),
        ),

        # --- WeatherRecord（気象記録）---
        # observed_at は unique=True 制約付き。
        # → 同じ観測時刻のレコードを2回作れないことをDBレベルで保証する。
        # → 1時間ごとの気象データを重複保存しないための仕掛け。
        migrations.AlterField(
            model_name='weatherrecord',
            name='observed_at',
            field=models.DateTimeField(unique=True, verbose_name='観測時刻'),
        ),
        migrations.AlterField(
            model_name='weatherrecord',
            name='pressure_hpa',
            field=models.FloatField(verbose_name='気圧(hPa)'),
        ),
        migrations.AlterField(
            model_name='weatherrecord',
            name='temperature_c',
            field=models.FloatField(verbose_name='気温(℃)'),
        ),
        # 天気コード（Open-Meteoの weathercode に準拠：0=晴 1=主に晴 2=曇 3=雨 ...）
        # default=2（曇）はデータ欠損時の安全側デフォルト
        migrations.AlterField(
            model_name='weatherrecord',
            name='weather_code',
            field=models.PositiveSmallIntegerField(default=2, verbose_name='天気コード'),
        ),
    ]