# Generated by Django 5.2.15 on 2026-06-29 05:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

def backfill_location_owner(apps, schema_editor):
    """既存の単一 UserLocation を最初のユーザーに紐付け、
    既存 WeatherRecord を全てその地点にぶら下げる。"""
    UserLocation = apps.get_model("tracker", "UserLocation")
    WeatherRecord = apps.get_model("tracker", "WeatherRecord")
    User = apps.get_model("auth", "User")

    first_user = User.objects.order_by("id").first()
    loc = UserLocation.objects.order_by("id").first()  # 既存の単一レコード

    if loc and first_user and loc.user_id is None:
        loc.user = first_user
        loc.save()
    if loc:
        WeatherRecord.objects.filter(location__isnull=True).update(location=loc)

class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_painrecord_user_remindersetting_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weatherrecord',
            options={},
        ),
        migrations.AddField(
            model_name='userlocation',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー'),
        ),
        migrations.AddField(
            model_name='weatherrecord',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tracker.userlocation', verbose_name='観測地点'),
        ),
        migrations.AlterField(
            model_name='weatherrecord',
            name='observed_at',
            field=models.DateTimeField(verbose_name='観測時刻'),
        ),
        migrations.AddIndex(
            model_name='weatherrecord',
            index=models.Index(fields=['location', 'observed_at'], name='tracker_wea_locatio_4e7e57_idx'),
        ),
        migrations.AddConstraint(
            model_name='weatherrecord',
            constraint=models.UniqueConstraint(fields=('location', 'observed_at'), name='uq_weather_loc_time'),
        ),
        migrations.RunPython(backfill_location_owner, migrations.RunPython.noop),
    ]
