# Generated by Django 5.2.15 on 2026-07-03 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_alter_weatherrecord_options_userlocation_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weatherrecord',
            options={'ordering': ['-observed_at']},
        ),
        migrations.RemoveConstraint(
            model_name='weatherrecord',
            name='uq_weather_loc_time',
        ),
        migrations.RemoveIndex(
            model_name='weatherrecord',
            name='tracker_wea_locatio_4e7e57_idx',
        ),
        migrations.RemoveField(
            model_name='userlocation',
            name='user',
        ),
        migrations.RemoveField(
            model_name='weatherrecord',
            name='location',
        ),
        migrations.AddField(
            model_name='weatherrecord',
            name='is_forecast',
            field=models.BooleanField(default=False, verbose_name='予報フラグ'),
        ),
        migrations.AlterField(
            model_name='weatherrecord',
            name='observed_at',
            field=models.DateTimeField(unique=True, verbose_name='観測時刻'),
        ),
    ]
